### PR TITLE
feat: add jsonrpc batch support to Django

### PR DESCRIPTION
**Pull request by vasilcovsky**
### Description of the Change

 * **[new]** Django's request object is injected into parameters of each rpc request
 * **[removed]** logging for consistency with #82

### CODE REVIEW

**Comment by igor-v-wqpredtech** [comment]
Hi @pavlov99,

imho it make sense completely remove logging in backend.django to conform with https://github.com/pavlov99/json-rpc/pull/82

**Comment by vasilcovsky** [comment]
Hi @pavlov99,

imho it makes sense completely remove logging in backend.django to conform with #82

**Comment by pavlov99** [comment]
If logging is removed in one place, it makes sense to remove it in the other.
Let me take a loser look at your suggestion!

**Comment by vasilcovsky** [comment]
> If logging is removed in one place, it makes sense to remove it in the other.

pushed change without logging

**Comment by vasilcovsky** [comment]
@pavlov99 were you able to take a look?

**Comment by vasilcovsky** [comment]
@pavlov99, this pr adds batch support to django. Can you take a look please?

**Review by pavlov99 — APPROVED** [review]

**Pull request merged**
