### PR TITLE
Correct UnboundLocalError

### PR DESCRIPTION
**Pull request by sethrh**
This corrects is a somewhat obscure error that occurs when a jsonrpc method has PEP3107 annotations, and is then called with incorrect parameters.

### CODE REVIEW

**Comment by pavlov99** [comment]
Good job! Unfortunately, tests have failed, so we need to figure it out first. Issue is with import, should not be hard.

**Comment by S1983tt** [comment]
> This corrects is a somewhat obscure error that occurs when a jsonrpc method has PEP3107 annotations, and is then called with incorrect parameters.
> 

https://github.com/pavlov99/json-rpc/pull/45

**Comment by pavlov99** [comment]
Could you please rebase? Github says that the merge contains 378 commits.

**Comment by sethrh** [comment]
I'm sorry, I have no memory of this PR. Has this been hanging since 2016 or did something else happen recently to reanimate it?

**Pull request closed without merging**
