### PR TITLE
Makes RPC endpoint CSRF exempt

### PR DESCRIPTION
**Pull request by arnuschky**

### CODE REVIEW

**Comment by pavlov99** [comment]
build is broken, one need to fix tests first.

**Comment by pavlov99** [comment]
@arnuschky another thing here: there are several ways to provide authentication on the server side, each of them would lead to different security mechanisms. In case of default Django cookie-based authentication one need to use CSRF and your pull request is perfectly valuable. From another hand, if there is token-based authentication (OAUTH1/2), there are no cookies, including CSRF. If developer chooses to use this approach,  library should not force to use csrf (because it is simply redundant).

If you would like to contribute csrf mechanism, I would suggest to inherit  from `JSONRPCAPI` class and redefine `jsonrpc` method, something like this:

```python
class JSONRPCAPICSRF(JSONRPCAPI):
    def jsonrpc(self, request):
        return csrf_exempt(super(JSONRPCAPICSRF, self).jsonrpc)(self, request)
```

In this case current code still would work and new functionality would be implemented in a proper way.

**Comment by arnuschky** [comment]
I think there's a misunderstanding: my patch *disabled* CSRF protection on the API endpoint. This is commonly done for API endpoints, as there might be no GUI form that the client can get the CSRF token from. This is also why typically, token-based auth is used.

I can use the subclassing, but the current behavior goes against common behavior of other API libs. I can also add a setting if desired.

Sorry for the tests, I can fix it if need be.

**Comment by pavlov99** [comment]
@arnuschky it was misunderstanding from my side, indeed. I agree with code implementation. Please fix tests and we merge this feature.

**Comment by arnuschky** [comment]
ok, will do. Was wondering already what was going on in the tests. :)

**Comment by pavlov99** [comment]
@arnuschky merged and released: https://pypi.python.org/pypi/json-rpc/1.10.3

**Comment by arnuschky** [comment]
Great, thanks!

**Pull request merged**
