### PR TITLE
Remove redundant json parsing

### PR DESCRIPTION
**Pull request by smagafurov**

### CODE REVIEW

**Comment by smagafurov** [comment]
@pavlov99, hi!

This pull request removes redundant json parsing
But Travis failed because of InterpreterNotFound error for py26, py33 and pypy
What can we do with this?

**Comment by pavlov99** [comment]
@smagafurov let me take a look. Likely need to remove unsupported python versions and move to circleci.

**Comment by smagafurov** [comment]
@pavlov99 removed unsupported python versions

Travis passed

Can we merge and release minor version?

**Comment by pavlov99** [comment]
Dear all, please refer to this comment: https://github.com/pavlov99/json-rpc/issues/74#issuecomment-340273475

**Pull request closed without merging**
